version: '3'

services:
  personblog_postgresql:
    image: postgres:12
    container_name: personblog_postgresql
    volumes:
      - personblog_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - personblog_network



volumes:
  personblog_postgresql:
    external: true

networks:
  personblog_network:
    external: true



